backend:
  name: git-gateway
  branch: main
  login: true

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "hero"
    label: "Hero"
    files:
      - file: "content/hero.json"
        label: "Hero Section"
        name: "hero"
        fields:
          - {label: "Заголовок", name: "title", widget: "string"}
          - {label: "Описание", name: "subtitle", widget: "text"}
          - {label: "Текст", name: "description", widget: "text"}

  - name: "about"
    label: "About"
    files:
      - file: "content/about.json"
        label: "Обо мне"
        name: "about"
        fields:
          - {label: "Заголовок", name: "title", widget: "string"}
          - {label: "Подзаголовок", name: "subtitle", widget: "string"}
          - {label: "Текст 1", name: "p1", widget: "text"}
          - {label: "Текст 2", name: "p2", widget: "text"}

  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Название", name: "title", widget: "string"}
      - {label: "Описание", name: "description", widget: "text"}

  - name: "works"
    label: "Works"
    folder: "content/works"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Название", name: "title", widget: "string"}
      - {label: "Категория", name: "category", widget: "string"}
      - {label: "Изображение", name: "image", widget: "image"}
      - {label: "Описание", name: "description", widget: "text"}

  - name: "contacts"
    label: "Contacts"
    files:
      - file: "content/contacts.json"
        label: "Контакты"
        name: "contacts"
        fields:
          - {label: "Ник", name: "nick", widget: "string"}
          - {label: "Telegram", name: "telegram", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
